cart/urls.py
from django.urls import path
from .views import cart , cart_add , cart_remove , add_quantity

app_name = 'cart'

urlpatterns = [
    path('' ,cart,name='cart'),
    path('add/<int:product_id>' ,cart_add,name='cart_add'),
    path('add/quantity/<int:product_id>',add_quantity,name='add_quantity'),
    path('remove,<int:product_id>' ,cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include ,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('shop.urls')),
    path('account/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('dashboard/',include('dashboard.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import detail , create

app_name = 'orders'

urlpatterns = [
    path('<int:order_id>', detail ,name='detail'),
    path('create' , create ,name='create')
]

shop/urls.py
from django.urls import path
from .views import home , detail , category_detail , add_reply , search

app_name = 'shop'
urlpatterns = [
    path('',home,name='home'),
    path('page/<int:page>',home,name='home'),
    path('search',search,name='search'),
    path('detail/<slug:slug>',detail,name='detail'),
    path('reply/<slug:product_slug>/<int:comment_pk>',add_reply,name='add-reply'),
    path('category/<slug:slug>',category_detail,name='category_detail'), ]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from .cart import Cart
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.models import Product
# Create your views here.

@login_required
def cart(request):
    cart = Cart(request)
    return render(request,'cart/cart.html',{'cart':cart})

@login_required
@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,pk=product_id)
    quantity = request.POST['quantity']
    quantity = int(quantity)
    cart.add(product=product,quantity=quantity)
    return redirect('cart:cart')


@login_required
@require_POST
def add_quantity(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,pk=product_id)
    quantity = request.POST['quantity']
    quantity = int(quantity)
    cart.add_quantity(product=product,quantity=quantity)
    return redirect('cart:cart')

@login_required
def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,pk=product_id)
    cart.remove(product)
    return redirect('cart:cart')

templates/cart/cart.html
{% extends 'base.html' %}

{% block title %} Cart {% endblock %}

{% block content %}
 
 <main class="ps-main">
  <div class="ps-content pt-80 pb-80">
    <div class="ps-container">
      <div class="ps-cart-listing">
        <table class="table ps-cart__table">
          <thead>
            <tr>
              <th>All Products</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Total</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for item in cart %}
                <tr>
                    <td><a class="ps-product__preview" href="{% url 'shop:detail' item.product.pk %}"><img class="mr-15" style="width: 100px; height :100px" src="{{item.product.photo.url}}" alt=""> {{item.product}}</a></td>
                    <td>{{item.price}}</td>
                    <td>
                      <form method="POST" action="{% url 'cart:add_quantity' item.product.pk %}">
                        {% csrf_token %}
                      <input type="number" name='quantity' value="{{item.quantity}}"  min="1" max="100" >
                      <button type="submit">ADD</button>
                      </form>
                      </div>
                    </td>
                    <td>{{item.total_price}}</td>
                    <td>
                      <a href="{% url 'cart:cart_remove' item.product.pk %}"><div class="ps-remove"></div></a>
                    </td>
                </tr>
            {% endfor %}
         
          </tbody>
        </table>
        <div class="ps-cart__actions">
          <div class="ps-cart__promotion">
            <div class="form-group">
              <div class="ps-form--icon"><i class="fa fa-angle-right"></i>
                <input class="form-control" type="text" placeholder="Promo Code">
              </div>
            </div>
            <div class="form-group">
              <button class="ps-btn ps-btn--gray">Continue Shopping</button>
            </div>
          </div>
          <div class="ps-cart__total">
            <h3>Total Price: <span> {{cart.get_total_price}}</span></h3><a class="ps-btn" href="{% url 'orders:create' %}">Process to checkout<i class="ps-icon-next"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}