accounts/urls.py
from django.urls import path
from .views import loginUser , LogoutUser , RegisterUser , userorder , user_order_detail

app_name = 'accounts'

urlpatterns = [
    path('login/',loginUser,name='login'),
    path('logout/',LogoutUser,name='logout'),
    path('register/',RegisterUser,name='register'),
    path('order/',userorder,name='user_order'),
    path('order/<int:pk>',user_order_detail,name='user_order_detail'),
]

cart/urls.py
from django.urls import path
from .views import cart , cart_add , cart_remove , add_quantity

app_name = 'cart'

urlpatterns = [
    path('' ,cart,name='cart'),
    path('add/<int:product_id>' ,cart_add,name='cart_add'),
    path('add/quantity/<int:product_id>',add_quantity,name='add_quantity'),
    path('remove,<int:product_id>' ,cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include ,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('shop.urls')),
    path('account/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('dashboard/',include('dashboard.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import (ProductList , CreateProduct , PreviewProduct , UpdateProduct , DeleteProduct , OrderList,
OrderDetail , DeleteOrder , UserList , UserDetail , DeleteUser)

app_name = 'dashboard'
urlpatterns = [
    path('',ProductList.as_view(),name='index'),
    path('page/<int:page>',ProductList.as_view(),name='index'),
    path('create', CreateProduct.as_view(), name = 'create'),
    path('preview/<int:pk>', PreviewProduct.as_view(), name = 'preview'),
    path('update/<int:pk>', UpdateProduct.as_view(), name = 'update'),
    path('delete/<int:pk>', DeleteProduct.as_view(), name = 'delete-product'),
    path('order',OrderList.as_view(),name='order'),
    path('order/<int:pk>',OrderDetail.as_view(),name='order-detail'),
    path('delete/order/<int:pk>', DeleteOrder.as_view(), name = 'delete-order'),
    path('user/list', UserList.as_view(), name = 'user-list'),
    path('user/<int:pk>',UserDetail.as_view(),name='user-detail'),
    path('delete/user/<int:pk>', DeleteUser.as_view(), name = 'delete-user'),
    
]

shop/urls.py
from django.urls import path
from .views import home , detail , category_detail , add_reply , search

app_name = 'shop'
urlpatterns = [
    path('',home,name='home'),
    path('page/<int:page>',home,name='home'),
    path('search',search,name='search'),
    path('detail/<slug:slug>',detail,name='detail'),
    path('reply/<slug:product_slug>/<int:comment_pk>',add_reply,name='add-reply'),
    path('category/<slug:slug>',category_detail,name='category_detail'), ]

templates/partials/cart_item.html
<div class="ps-cart"><a class="ps-cart__toggle" href="#"><span><i>20</i></span><i class="ps-icon-shopping-cart"></i></a>
    <div class="ps-cart__listing">
      <div class="ps-cart__content">
        <div class="ps-cart-item"><a class="ps-cart-item__close" href="#"></a>
          <div class="ps-cart-item__thumbnail"><a href="product-detail.html"></a><img src="images/cart-preview/1.jpg" alt=""></div>
          <div class="ps-cart-item__content"><a class="ps-cart-item__title" href="product-detail.html">Amazin’ Glazin’</a>
            <p><span>Quantity:<i>12</i></span><span>Total:<i>£176</i></span></p>
          </div>
        </div>
      </div>
      <div class="ps-cart__total">
        <p>Number of items:<span>{{cart.count}}</span></p>
        <p>Item Total:<span>£528.00</span></p>
      </div>
      <div class="ps-cart__footer"><a class="ps-btn" href="cart.html">Check out<i class="ps-icon-arrow-left"></i></a></div>
    </div>
  </div>

templates/partials/category_navbar.html
<div class="navigation__column center">
  <ul class="main-menu menu">
    <li class="menu-item menu-item-has-children dropdown"><a href="{% url 'shop:home' %}">Home</a></li>
      {% for cat in category %}
        {% if cat.subcat == None %}
          <li class="menu-item menu-item-has-children dropdown">
            <a href="{% url 'shop:category_detail' cat.slug %}">{{cat.name}}</a>
            {% if cat.scat.subcategory %}
              {% include 'partials/category_navbarloop.html' %}
            {% endif %}
          </li>
        {% endif %}
      </li>
      {% endfor %}
  </ul>
</div>

templates/partials/category_navbarloop.html
<ul class="sub-menu">         
    {% for cat in cat.scat.subcategory %}
    <li class="menu-item menu-item-has-children dropdown"><a href="{% url 'shop:category_detail' cat.slug %}">{{cat.name}}</a>
        {% if cat.scat.subcategory %}
            {% include 'partials/category_navbarloop.html' %}
        {% endif %}       
    </li>      
    {% endfor %}
</ul>

templates/partials/footer.html
<div class="ps-footer bg--cover" data-background="images/background/parallax.jpg">
<div class="ps-footer__copyright">
    <div class="ps-container">
      <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
              <p>&copy; <a href="#">SKYTHEMES</a>, Inc. All rights Resevered. Design by <a href="#"> Alena Studio</a></p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
              <ul class="ps-social">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
      </div>
    </div>
</div>
</div>

templates/partials/header.html
<div class="header--sidebar"></div>
    <header class="header">
      <div class="header__top">
        <div class="container-fluid">
          <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-6 col-xs-12 ">
                  <p>460 West 34th Street, 15th floor, New York  -  Hotline: 804-377-3580 - 804-399-3580</p>
                </div>
                <div class="col-lg-6 col-md-4 col-sm-6 col-xs-12 ">
                {% if user.is_authenticated  %}
                <div class="header__actions"><a href="{% url 'accounts:logout' %}">Logout</a> </div>
                <div class="header__actions"><a href="#">Welcome {{user.first_name}}</a> </div>
                <div class="header__actions"><a href="{% url 'accounts:user_order' %}">My Orders</a> </div>
                  {% if user.is_authenticated and user.is_shopadmin or user.is_admin %}
                    <div class="header__actions"><a href="{% url 'dashboard:index' %}">Dashboard</a> </div>
                  {% endif %}
                {% else %}
                <div class="header__actions"><a href="{% url 'accounts:login' %}">Login</a> </div>
                <div class="header__actions"><a href="{% url 'accounts:register' %}">Register</a> </div>
                {% endif %}
             </div>
        </div>
    </div>
</div>

templates/partials/message.html
{% if message %}
    {% for msg in message %}
        <p class="alert alert-{{ msg.tags }}">{{msg}}</p>
    {% endfor %}
    
{% endif %}

templates/partials/navbar.html
{% load base_tags %}

<nav class="navigation">
    <div class="container-fluid">
      <div class="navigation__column left">
        <div class="header__logo"><a class="ps-logo" href="index.html"><img src="images/logo.png" alt=""></a></div>
      </div>
     
              
      {% category_navbar %}
            
      <div class="navigation__column right">
        <form class="ps-search--header" action="{% url 'shop:search' %}"  method="get">
          <input name="search">
          <button type="submit"><i class="ps-icon-search"></i></button>
        </form>
        <div class="ps-cart">
          <a class="ps-cart__toggle" href="{% url 'cart:cart' %}"><span></span>
            </span><i class="ps-icon-shopping-cart"></i></a>
            
        </div>
      </div>
    </div>
</nav>