cart/urls.py
from django.urls import path
from .views import cart , cart_add , cart_remove , add_quantity

app_name = 'cart'

urlpatterns = [
    path('' ,cart,name='cart'),
    path('add/<int:product_id>' ,cart_add,name='cart_add'),
    path('add/quantity/<int:product_id>',add_quantity,name='add_quantity'),
    path('remove,<int:product_id>' ,cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include ,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('shop.urls')),
    path('account/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('dashboard/',include('dashboard.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import home , detail , category_detail , add_reply , search

app_name = 'shop'
urlpatterns = [
    path('',home,name='home'),
    path('page/<int:page>',home,name='home'),
    path('search',search,name='search'),
    path('detail/<slug:slug>',detail,name='detail'),
    path('reply/<slug:product_slug>/<int:comment_pk>',add_reply,name='add-reply'),
    path('category/<slug:slug>',category_detail,name='category_detail'), ]

shop/models.py
from django.db import models
from django.utils.html import format_html
from django.shortcuts import reverse

# Create your models here.

class CategoryManager(models.Manager):
    def subcategory(self):
        return self.filter(is_subcat = True)

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True)
    subcat = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='scat')
    is_subcat = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']  
        verbose_name_plural = 'categories'

    objects = CategoryManager()

class Product(models.Model):
    STATUS_CHOICES = (
        ('d','draft'),
        ('p','published')
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True)
    category = models.ManyToManyField(Category,related_name='cat')
    photo = models.ImageField(upload_to = 'product/%Y/%M/%d')
    description = models.TextField()
    storage = models.IntegerField()
    available = models.BooleanField(default=True)
    price = models.IntegerField()
    status = models.CharField(max_length=1,choices=STATUS_CHOICES,default='d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    
    class Meta:
        ordering = ['status','-created'] 
        
    def __str__(self):
        return self.name

    def image_tag(self):
        return format_html("<img src='{}' width =60 height=50>".format(self.photo.url))
    image_tag.short_description = 'photo'    


    def category_to_str(self):
        return '-'.join([category.name for category in self.category.all()])


    def get_absolute_url(self):
        return reverse('dashboard:index')

shop/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Product , Category 
from comments.models import Comment
from comments.forms import CommentForm
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.

def home(request,page=1):
    products_list = Product.objects.filter(available=True,status='p')
    paginator = Paginator(products_list,4)
    products = paginator.get_page(page)
    if 'search' in request.GET:
        search = request.GET['search']
        products = products.filter(Q(name__icontains=search) | Q(description__icontains=search))
    return render(request,'shop/index.html',{'products':products,})


def detail(request,slug):
    product = get_object_or_404(Product,slug=slug,status='p')
    comment = Comment.objects.filter(product=product)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            newcomment = form.save(commit=False)
            newcomment.user = request.user
            newcomment.product = product
            newcomment.save()
    else:
        form = CommentForm()
    return render(request,'shop/detail.html',{'product':product,'comment':comment,'form':form}) 


def category_detail(request,slug):
    category = get_object_or_404(Category,slug=slug)
    product = category.cat.filter(available=True)
    return render(request,'shop/index.html',{'products':product}) 


def add_reply(request,product_slug,comment_pk):
    product = get_object_or_404(Product,slug=product_slug)
    comment = get_object_or_404(Comment,pk=comment_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            newreply = form.save(commit=False)
            newreply.user = request.user
            newreply.product = product
            newreply.reply = comment
            newreply.is_reply = True
            newreply.save()
            return redirect('shop:detail',product_slug)
    return render(request,'shop/replycm_loop.html',{'form':form})


def search(request):
    products = Product.objects.filter(available=True)
    if 'search' in request.GET:
        search = request.GET['search']
        products = products.filter(Q(name__icontains=search) | Q(description__icontains=search))
    return render(request,'shop/index.html',{'products':products,})

templates/shop/detail.html
{% extends 'base.html' %}
{% load ratings %}

{% block title %} Detail {% endblock %}

{% block content %}
 <div class="ps-product--detail pt-60">
        <div class="ps-container">
          <div class="row">
            <div class="col-lg-10 col-md-12 col-lg-offset-1">
              <div class="ps-product__thumbnail">
                <div class="ps-product__image">
                  <div class="item"><img class="zoom" src="{{product.photo.url}}" alt="" data-zoom-image="images/shoe-detail/3.jpg"></div>
                </div>
              </div>
             
              <div class="ps-product__info">
                <div class="ps-product__rating">
                  {% ratings product %}
                </div>
                <h1>{{product.name}}</h1>
                <p>The storage is {{product.price}}</p>
                <p class="ps-product__category">
                  {% for cat in product.category.all %}
                  <a href="{% url 'shop:category_detail' cat.slug %}"> #{{cat.name}}</a>
                  {% endfor %}
                </p>
                <h3 class="ps-product__price">£ {{product.price}}</h3>
                <div class="ps-product__shopping">
                  <form method="POST" action="{% url 'cart:cart_add' product.pk %}">
                    {% csrf_token %}
                    <input type="hidden" value="1" name='quantity'>
                    <button class="ps-btn mb-10" >Add to cart<i class="ps-icon-next"></i></button>
                  </form>
                </i></a>
                </div>
              </div>
              <div class="clearfix"></div>
              <div class="ps-product__content mt-50">
                <ul class="tab-list" role="tablist">
                  <li class="active"><a href="#tab_01" aria-controls="tab_01" role="tab" data-toggle="tab">Overview</a></li>
                  <li><a href="#tab_02" aria-controls="tab_02" role="tab" data-toggle="tab">Review</a></li>
                </ul>
              </div>
              <div class="tab-content mb-60">
                <div class="tab-pane active" role="tabpanel" id="tab_01">
                  <p>{{product.description}}</p>
                </div>
                <div class="tab-pane" role="tabpanel" id="tab_02">
                  <p class="mb-20">{{comment.count}} review for <strong>{{product.name}}</strong></p>

<!-----------------------SHOW COMMNETS------------------------------------------>          
                  {% for cm in comment %}
                    {% if cm.reply == None %}
                      <div class="ps-review">
                        <div class="ps-review__content">
                          <header>
                            <p>By <a href="">{{cm.user}}</a>{{cm.created}}</p> <button onclick="myFunction()" >reply</button>
                          </header>
                          <p>{{cm.body}}</p>
<!-----------------------ADD COMMENT REPLY  ------------------------------------------>  
                   
                          <form id='repcm' action="{% url 'shop:add-reply' product.slug cm.pk  %}" class="ps-product__review" method="post" style="display: none;">
                            {% csrf_token %}
                            <div class="row">
                                  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                                    <div class="form-group">
                                      {{form.body}}
                                    </div>
                                    <!---rating-->
                                    <div class="form-group">
                                      <button class="ps-btn ps-btn--sm">Submit<i class="ps-icon-next"></i></button>
                                    </div>
                                  </div>
                            </div>
                          </form>
<!-----------------------END ADD REPLY------------------------------------------>
<!-----------------------SHOW REPLY COMMNETS------------------------------------>
                          {% if cm.romment.reply %}
                            {% include 'shop/replycm_loop.html' %}
                          {% endif %}
<!-----------------------END SHOW REPLY COMMNETS-------------------------------->
                        </div>
                      </div>
                    {% endif %}
                  {% endfor %}

<!-----------------------END SHOW COMMNETS-------------------------------->


<!-----------------------ADD  COMMNETS------------------------------------->

                  <form class="ps-product__review" method="post">
                    {% csrf_token %}
                    <h4>ADD YOUR REVIEW</h4>
                    <div class="row">
                          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                            <div class="form-group">
                              <label>Your Review:</label>
                              {{form.body}}
                            </div>
                            <!---rating-->
                            <div class="form-group">
                              <button class="ps-btn ps-btn--sm">Submit<i class="ps-icon-next"></i></button>
                            </div>
                          </div>
                    </div>
                  </form>
<!-----------------------END ADD COMMNETS-------------------------------->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<script>
        function myFunction() {
          var x = document.getElementById("repcm");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }
        }
  </script>
        

{% endblock %}

templates/shop/index.html
{% extends 'base.html' %}
{% load ratings %}

{% block title %} Home {% endblock %}

{% block content %}
<h1>{{name}}</h1>

<div class="ps-section--features-product ps-section masonry-root pt-100 pb-100">
    <div class="ps-container">

      <div class="ps-section__content pb-50">
        <div class="masonry-wrapper" data-col-md="4" data-col-sm="2" data-col-xs="1" data-gap="30" data-radio="100%">
          <div class="ps-masonry">
            <div class="grid-sizer"></div>

            {% for product in products %}
            <div class="grid-item kids">
            <div class="grid-item__content-wrapper">
              <div class="ps-shoe mb-30">
                <div class="ps-shoe__thumbnail">
                <img src="{{product.photo.url}}" alt="{{product.name}}" style="width: 250px; height:300px"><a class="ps-shoe__overlay" href="{% url 'shop:detail' product.slug %}"></a>
                </div>
                <div class="ps-shoe__content">
                  <div class="ps-shoe__variants">
                    {% ratings product %}
                  </div>
                  <div class="ps-shoe__detail">
                    <p class="ps-shoe__categories">{{product.name}}</p>
                    
                    <span class="ps-shoe__price">{{product.price}}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          </div>
        </div>
      </div>

<!-----------------------Pagination--------------------------->
{% if products.has_other_pages %}
<div class="row">
  <div class="col-sm-12 col-md-5">
  </div>
  <div class="col-sm-12 col-md-7">
    <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
      <ul class="pagination">
        {% if products.has_previous %}
        <li class="paginate_button page-item previous " id="dataTable_previous">
          <a href="{% url 'shop:home' products.previous_page_number %}" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="paginate_button page-item previous disabled" id="dataTable_previous">
          <a  aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% endif %}
       {% for i in products.paginator.page_range %}
        {% if products.number == i %}
        <li class="paginate_button page-item active">
          <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="paginate_button page-item ">
          <a href="{% url 'shop:home' i %}" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% endif %}
       {% endfor %}
        {% if products.has_next %}
        <li class="paginate_button page-item next" id="dataTable_next">
          <a href="{% url 'shop:home' products.next_page_number %}" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="paginate_button page-item next disabled" id="dataTable_next">
          <a aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
<!-----------------------End Pagination--------------------------->
{% endif %}

    </div>
  </div>
  


{% endblock %}

templates/shop/replycm_loop.html
<!-----------------------SHOW COMMNETS----------------------------------------->

    {% for cm in cm.romment.reply %}
    <p>------------------------------------------------------------------------------</p>
        <div class="ps-review">
          <div class="ps-review__content">
            <header>
              <p>Reply by <a href="">{{cm.user}}</a>{{cm.created}}</p> <button onclick="myFunction2()" >reply</button>
            </header>
            <p>{{cm.body}}</p>
<!-----------------------ADD COMMENT REPLY  ------------------------------------------>  
                   
            <form id='repcmloop' action="{% url 'shop:add-reply' product.slug cm.pk  %}" class="ps-product__review" method="post" style="display: none;">
              {% csrf_token %}
              <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                      <div class="form-group">
                        {{form.body}}
                      </div>
                      <!---rating-->
                      <div class="form-group">
                        <button class="ps-btn ps-btn--sm">Submit<i class="ps-icon-next"></i></button>
                      </div>
                    </div>
              </div>
            </form>
<!-----------------------END ADD REPLY------------------------------------------>
<!-----------------------SHOW REPLY COMMNETS------------------------------------>
            {% if cm.romment.reply %}
              {% include 'shop/replycm_loop.html' %}
            {% endif %}
<!-----------------------END SHOW REPLY COMMNETS-------------------------------->
          </div>
        </div>

    {% endfor %}

<!-----------------------END SHOW COMMNETS-------------------------------->


<script>
  function myFunction2() {
    var x = document.getElementById("repcmloop");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>