accounts/urls.py
from django.urls import path
from .views import loginUser , LogoutUser , RegisterUser , userorder , user_order_detail

app_name = 'accounts'

urlpatterns = [
    path('login/',loginUser,name='login'),
    path('logout/',LogoutUser,name='logout'),
    path('register/',RegisterUser,name='register'),
    path('order/',userorder,name='user_order'),
    path('order/<int:pk>',user_order_detail,name='user_order_detail'),
]

cart/urls.py
from django.urls import path
from .views import cart , cart_add , cart_remove , add_quantity

app_name = 'cart'

urlpatterns = [
    path('' ,cart,name='cart'),
    path('add/<int:product_id>' ,cart_add,name='cart_add'),
    path('add/quantity/<int:product_id>',add_quantity,name='add_quantity'),
    path('remove,<int:product_id>' ,cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include ,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('shop.urls')),
    path('account/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('dashboard/',include('dashboard.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import (ProductList , CreateProduct , PreviewProduct , UpdateProduct , DeleteProduct , OrderList,
OrderDetail , DeleteOrder , UserList , UserDetail , DeleteUser)

app_name = 'dashboard'
urlpatterns = [
    path('',ProductList.as_view(),name='index'),
    path('page/<int:page>',ProductList.as_view(),name='index'),
    path('create', CreateProduct.as_view(), name = 'create'),
    path('preview/<int:pk>', PreviewProduct.as_view(), name = 'preview'),
    path('update/<int:pk>', UpdateProduct.as_view(), name = 'update'),
    path('delete/<int:pk>', DeleteProduct.as_view(), name = 'delete-product'),
    path('order',OrderList.as_view(),name='order'),
    path('order/<int:pk>',OrderDetail.as_view(),name='order-detail'),
    path('delete/order/<int:pk>', DeleteOrder.as_view(), name = 'delete-order'),
    path('user/list', UserList.as_view(), name = 'user-list'),
    path('user/<int:pk>',UserDetail.as_view(),name='user-detail'),
    path('delete/user/<int:pk>', DeleteUser.as_view(), name = 'delete-user'),
    
]

shop/urls.py
from django.urls import path
from .views import home , detail , category_detail , add_reply , search

app_name = 'shop'
urlpatterns = [
    path('',home,name='home'),
    path('page/<int:page>',home,name='home'),
    path('search',search,name='search'),
    path('detail/<slug:slug>',detail,name='detail'),
    path('reply/<slug:product_slug>/<int:comment_pk>',add_reply,name='add-reply'),
    path('category/<slug:slug>',category_detail,name='category_detail'), ]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render , redirect , Http404 , get_object_or_404 
from django.urls import reverse_lazy
from django.views.generic import (CreateView , ListView , DetailView , UpdateView , DeleteView)
from shop.models import Product
from .mixins import (AccessUserMixin,FieldMixin , FormValifMixin , AccessMixin , DetailViewMixin ,
AccessDeleteMixin )
from orders.models import Order 
from accounts.models import User
# Create your views here.

class ProductList(ListView):
    template_name = 'dashboard/product_list.html'
    paginate_by = 6
    def get_queryset(self):
        if self.request.user.is_admin or self.request.user.is_shopadmin:
            return Product.objects.all()
        else:
            raise Http404("You don't have access to this page")


class CreateProduct(AccessUserMixin,FieldMixin,FormValifMixin,CreateView):
    model = Product
    template_name = 'dashboard/product_create.html'


class PreviewProduct(AccessUserMixin,DetailView):
    template_name = 'shop/detail.html'
    def get_object(self):
        pk = self.kwargs.get('pk')
        global product
        product  = get_object_or_404(Product,pk=pk)
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = product
        return context


class UpdateProduct(AccessMixin,FieldMixin,FormValifMixin,UpdateView):
    model = Product
    template_name = 'dashboard/product_create.html'


class DeleteProduct(AccessMixin,DeleteView):
    model = Product
    template_name = 'dashboard/delete.html'
    success_url = reverse_lazy('dashboard:index')


class OrderList(ListView):
    template_name = 'dashboard/order_list.html'
    paginate_by = 6
    def get_queryset(self):
        if self.request.user.is_admin or self.request.user.is_shopadmin:
            return Order.objects.all()
        else:
            raise Http404("You don't have access to this page")


class OrderDetail(AccessUserMixin,DetailViewMixin, UpdateView):
    details_model = Order
    context_detail_object_name = 'order_item'
    model = Order
    template_name = 'dashboard/orderdetail.html'
    fields = ['status']


class DeleteOrder(AccessDeleteMixin,DeleteView):
    model = Order
    template_name = 'dashboard/delete.html'
    success_url = reverse_lazy('dashboard:order')


class UserList(AccessDeleteMixin,ListView):
    template_name = 'dashboard/access_user.html'
    paginate_by = 6
    def get_queryset(self):
        if self.request.user.is_admin:
            return User.objects.all()
        else:
            raise Http404("You don't have access to this page")


class UserDetail(AccessDeleteMixin,DetailViewMixin, UpdateView):
    details_model = User
    context_detail_object_name = 'user'
    model = User
    template_name = 'dashboard/detail_user.html'
    fields = ['is_shopadmin']


class DeleteUser(AccessDeleteMixin,DeleteView):
    model = User
    template_name = 'dashboard/delete.html'
    success_url = reverse_lazy('dashboard:user-list')

templates/dashboard/access_user.html
{% extends 'dashboard/base.html' %}

{% block title %} Access user {% endblock %}


{% block content %}

{% if object_list %}

<div class="card-header">
  <h3 class="card-title">Order List</h3>
</div>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>is admin</th>
        <th>is shopAdmin</th>
      </tr>
    </thead>
    <tbody>
        {% for user in object_list %}
      
        <tr>
          <td><a href="{% url 'dashboard:user-detail' user.pk %}">{{user.first_name}}</td>
          <td>{{user.last_name}}</td>
          <td>{{user.email}}</td>
          <td>
              {% if user.is_admin  %}
              <span class="fas fa-check" style="color: green;"></span>
              {% else %}
              <span class="fa fa-times" style="color: red;"></span>
              {% endif %}
          </td>
          <td>
            {% if user.is_shopadmin  %}
            <span class="fas fa-check" style="color: green;"></span>
            {% else %}
            <span class="fa fa-times" style="color: red;"></span>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
<!-- /.card-body -->

<!-----------------------Pagination--------------------------->
{% if page_obj.has_other_pages %}
<div class="row">
  <div class="col-sm-12 col-md-5">
  </div>
  <div class="col-sm-12 col-md-7">
    <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="paginate_button page-item previous " id="dataTable_previous">
          <a href="{% url 'dashboard:index' page_obj.previous_page_number %}" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="paginate_button page-item previous disabled" id="dataTable_previous">
          <a  aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% endif %}
       {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="paginate_button page-item active">
          <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="paginate_button page-item ">
          <a href="{% url 'dashboard:index' i %}" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% endif %}
       {% endfor %}
        {% if page_obj.has_next %}
        <li class="paginate_button page-item next" id="dataTable_next">
          <a href="{% url 'dashboard:index' page_obj.next_page_number %}" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="paginate_button page-item next disabled" id="dataTable_next">
          <a aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
<!-----------------------End Pagination--------------------------->
{% endif %}
{% else %}

<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">YouR shop doesn't have Order</h1>

</div>
<!-- /.container-fluid -->

{% endif %}
        
{% endblock %}

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} Dashboard page {% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'dashboard/partials/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                
    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                    
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="{% url 'shop:home' %}" id="alertsDropdown" role="button">
                                <span style="color: black;" >visit site</span> 
                            </a>
        
                        </li>

                       

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline small" style="color: black;" >{{user.first_name}} {{user.last_name}}</span>
            
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
               {% block content %}

               {% endblock %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'dashboard/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'dashboard/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'dashboard/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/dashboard/delete.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Page {% endblock %}

{% block content %}

<div class="col-md-6 text-center mx-autho" >
    <div class="card card-danger">
        <div class="card-header">
          <h3 class="card-title mb-0 float-left">Delete Product</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="post">
            {% csrf_token %}
            <p class="py-2">Are you sure delete {{object}} ?</p>
            
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-danger"> Delete</button>
          </div>
        </form>
      </div>
    </div>

{% endblock %}

templates/dashboard/detail_user.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block title %} User Detail {% endblock %}

{% block content %}

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title mb-0 float-left"> User Detail</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">{{user.first_name}}</h1>
            <h1 class="h3 mb-4 text-gray-800">{{user.last_name}}</h1>
          
          </div>
          <!-- /.container-fluid -->
          
        </div>
       
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-6 ">
                  {{ form.is_shopadmin|as_crispy_field }}
                </div>
            </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-primary"> submit </button>
            {% if  request.resolver_match.kwargs.pk %}
            <a href="{% url 'dashboard:delete-user' request.resolver_match.kwargs.pk %}"  class="btn btn-danger">Delete</a>
            {% endif %}
          </div>
        </form>
      </div>
    </div>


{% endblock %}

templates/dashboard/order_list.html
{% extends 'dashboard/base.html' %}

{% block title %} Order List {% endblock %}

{% block content %}

{% if object_list %}

<div class="card-header">
  <h3 class="card-title">Order List</h3>
</div>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>user</th>
        <th>total Price</th>
        <th>Paiment</th>
        <th>Sending</th>
      </tr>
    </thead>
    <tbody>
        {% for order in object_list %}
        <tr>
          <td><a href="{% url 'dashboard:order-detail' order.pk %}">{{order.user}}</td>
          <td>{{order.total_price}}</td>
          <td>
              {% if order.is_paid  %}
              <span class="fas fa-check" style="color: green;"></span>
              {% else %}
              <span class="fa fa-times" style="color: red;"></span>
              {% endif %}
          </td>
          <td>
            {% if order.status == 's' %}
              <span class="badge badge-success"> sent </span>
              {% elif order.status == 'o' %}
              <span class="badge badge-danger"> out of range </span>
              {% elif order.status == 'w' %}
              <span class="badge badge-warning"> waiting </span>
              {% elif order.status == 'p' %}
              <span class="badge badge-primary"> on proccess </span>
              {% endif %}
        </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
<!-- /.card-body -->

<!-----------------------Pagination--------------------------->
{% if page_obj.has_other_pages %}
<div class="row">
  <div class="col-sm-12 col-md-5">
  </div>
  <div class="col-sm-12 col-md-7">
    <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="paginate_button page-item previous " id="dataTable_previous">
          <a href="{% url 'dashboard:index' page_obj.previous_page_number %}" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="paginate_button page-item previous disabled" id="dataTable_previous">
          <a  aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% endif %}
       {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="paginate_button page-item active">
          <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="paginate_button page-item ">
          <a href="{% url 'dashboard:index' i %}" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% endif %}
       {% endfor %}
        {% if page_obj.has_next %}
        <li class="paginate_button page-item next" id="dataTable_next">
          <a href="{% url 'dashboard:index' page_obj.next_page_number %}" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="paginate_button page-item next disabled" id="dataTable_next">
          <a aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
<!-----------------------End Pagination--------------------------->
{% endif %}
{% else %}

<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">YouR shop doesn't have Order</h1>

</div>
<!-- /.container-fluid -->

{% endif %}
        
{% endblock %}

templates/dashboard/orderdetail.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Order Detail {% endblock %}

{% block content %}

<div class="card-header ">
    <h3 class="card-title">Order List</h3>

    <div class="card-tools">
      <div class="input-group input-group-sm" style="width: 150px;">
        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

        <div class="input-group-append">
          <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
        </div>
      </div>
    </div>
  </div>
  <!-- /.card-header -->
  <div class="card-body table-responsive p-0">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Item</th>
          <th>Price</th>
          <th>quantity</th>
          <th>get_cost</th>
        </tr>
      </thead>
      <tbody>
          {% for item in order_item.item.all %}
          <tr>
            <td>{{item.product}}</td>
            <td>{{item.price}}</td>
            <td>{{item.quantity}}</td>
            <td>{{item.get_cost}}</td>
          </tr>
         {% endfor %}
      </tbody>
    </table>
    <form method="POST">
      {% csrf_token %}
      {{ form.status|as_crispy_field }}
      <br>
      <button type="submit" class="btn btn-primary"> submit </button>
      {% if request.user.is_admin %}
      <a href="{% url 'dashboard:delete-order' order_item.pk %}"  class="btn btn-danger">Delete</a>
      {% endif %}
    </form>
  </div>
  <!-- /.card-body -->
        
{% endblock %}

templates/dashboard/product_create.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create Product {% endblock %}

{% block content %}

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title mb-0 float-left">Add Product</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="row">
                <div class="col-6 ">
                  {{ form.name|as_crispy_field }}
                  {{ form.slug|as_crispy_field }}
                </div>
                <div class="col-12 ">
                    {{ form.description|as_crispy_field }}
                </div>
                <div class="col-6 ">
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="col-6 ">
                    {{ form.photo|as_crispy_field }}
    
                </div>
                <div class="col-6 ">
                    {{ form.price|as_crispy_field }}
                </div>
                <div class="col-6 ">
                    {{ form.storage|as_crispy_field }}
                </div>
                {% if user.is_admin %}
                    <div class="col-6 ">
                        {{ form.status|as_crispy_field }}
                    </div>
                {% endif %}
                <div class="col-6 ">
                  {{ form.available|as_crispy_field }}
                </div>
            </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-primary"> submit </button>
            {% if  request.resolver_match.kwargs.pk %}
            <a href="{% url 'dashboard:delete-product' request.resolver_match.kwargs.pk %}"  class="btn btn-danger">Delete</a>
            {% endif %}
          </div>
        </form>
      </div>
    </div>


{% endblock %}

templates/dashboard/product_list.html
{% extends 'dashboard/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}
{% if object_list %}
<div class="card-header">
  <h3 class="card-title">Add Product</h3>
<!-- /.card-header -->
<div class="card-body table-responsive p-0">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>name</th>
        <th>photo</th>
        <th>description</th>
        <th>category</th>
        <th>price</th>
        <th>storage</th>
        <th>available</th>
        <th>status</th>
      </tr>
    </thead>
    <tbody>
        {% for product in object_list %}
        <tr>
          <td><a href="{% url 'dashboard:update' product.pk %}">{{product.name}}</a></td>
          <td><img src="{{product.photo.url}}" width="70" height="40"></td>
          <td>{{product.description|truncatewords:3}}</td>
          <td>{{product.category_to_str}}</td>
          <td>{{product.price}}</td>
          <td>{{product.storage}}</td>
          <td>
              {% if product.available  %}
              <span class="fas fa-check" style="color: green;"></span>
              {% else %}
              <span class="fa fa-times" style="color: red;"></span>
              {% endif %}
              </td>
          <td>
              {% if product.status == 'p' %}
              <span class="badge badge-success"> published </span>
              <a target="_blank" href="{% url 'shop:detail' product.slug %}" class="badge badge-primary">show in site</a>
              {% else %}
              <span class="badge badge-danger"> draft </span>
              <a target="_blank" href="{% url 'dashboard:preview' product.pk %}" class="badge badge-secondary"> Preview </a>
              {% endif %}
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>

<!-----------------------Pagination--------------------------->
{% if page_obj.has_other_pages %}
<div class="row">
  <div class="col-sm-12 col-md-5">
  </div>
  <div class="col-sm-12 col-md-7">
    <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="paginate_button page-item previous " id="dataTable_previous">
          <a href="{% url 'dashboard:index' page_obj.previous_page_number %}" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="paginate_button page-item previous disabled" id="dataTable_previous">
          <a  aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
        </li>
        {% endif %}
       {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="paginate_button page-item active">
          <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% else %}
        <li class="paginate_button page-item ">
          <a href="{% url 'dashboard:index' i %}" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">{{i}}</a>
        </li>
        {% endif %}
       {% endfor %}
        {% if page_obj.has_next %}
        <li class="paginate_button page-item next" id="dataTable_next">
          <a href="{% url 'dashboard:index' page_obj.next_page_number %}" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="paginate_button page-item next disabled" id="dataTable_next">
          <a aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
<!-----------------------End Pagination--------------------------->
{% endif %}

  <!-- /.card-body -->
{% else %}
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">YouR shop doesn't have product</h1>

</div>
<!-- /.container-fluid -->

</div>
{% endif %}
        
{% endblock %}